-- MySQL Script generated by MySQL Workbench
-- Thu Mar  8 07:55:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Suppliers` (
  `SupplierID` INT NOT NULL,
  `SupplierName` VARCHAR(45) NULL,
  `SupplierPhone` VARCHAR(45) NULL,
  `SupplierAddress` VARCHAR(45) NULL,
  `SupplierCity` VARCHAR(45) NULL,
  `SupplierZip` VARCHAR(45) NULL,
  PRIMARY KEY (`SupplierID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Materials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Materials` (
  `MaterialID` INT NOT NULL,
  `MaterialName` VARCHAR(45) NULL,
  `MaterialPricePerUnit` FLOAT NULL,
  PRIMARY KEY (`MaterialID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employees` (
  `EmployeeID` INT NOT NULL,
  `EmployeeFN` VARCHAR(45) NULL,
  `EmployeeLN` VARCHAR(45) NULL,
  `EmployeeSSN` VARCHAR(45) NULL,
  `EmployeePhone` VARCHAR(45) NULL,
  `EmployeeAddress` VARCHAR(45) NULL,
  `EmployeeCity` VARCHAR(45) NULL,
  `EmployeeZip` VARCHAR(45) NULL,
  `EmployeeDateHired` DATE NULL,
  `EmployeePayPerHour` FLOAT NULL,
  PRIMARY KEY (`EmployeeID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Purchases` (
  `PurchaseID` INT NOT NULL,
  `PurchaseDateTime` DATETIME(6) NULL,
  `PurchaseEmployee` INT NOT NULL,
  `PurchaseSupplier` INT NULL,
  `PurchasePrice` FLOAT NULL,
  PRIMARY KEY (`PurchaseID`, `PurchaseEmployee`),
  INDEX `PurchaseEmployee_idx` (`PurchaseEmployee` ASC),
  INDEX `PurchaseSupplier_idx` (`PurchaseSupplier` ASC),
  CONSTRAINT `PurchaseEmployee`
    FOREIGN KEY (`PurchaseEmployee`)
    REFERENCES `mydb`.`Employees` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PurchaseSupplier`
    FOREIGN KEY (`PurchaseSupplier`)
    REFERENCES `mydb`.`Suppliers` (`SupplierID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PurchaseInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PurchaseInfo` (
  `PurchaseID` INT NOT NULL,
  `Material` INT NULL,
  `MaterialQuantity` INT NULL,
  PRIMARY KEY (`PurchaseID`),
  INDEX `MaterialID_idx` (`Material` ASC),
  CONSTRAINT `PurchaseID`
    FOREIGN KEY (`PurchaseID`)
    REFERENCES `mydb`.`Purchases` (`PurchaseID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `MaterialID`
    FOREIGN KEY (`Material`)
    REFERENCES `mydb`.`Materials` (`MaterialID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Transactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Transactions` (
  `TransactionID` INT NOT NULL,
  `TransactionDateTime` DATETIME(6) NULL,
  `TransactionEmployee` INT NULL,
  `TransactionPrice` FLOAT NULL,
  PRIMARY KEY (`TransactionID`),
  INDEX `TransactionEmployee_idx` (`TransactionEmployee` ASC),
  CONSTRAINT `TransactionEmployee`
    FOREIGN KEY (`TransactionEmployee`)
    REFERENCES `mydb`.`Employees` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Products` (
  `ProductID` INT NOT NULL,
  `ProductName` VARCHAR(45) NULL,
  `ProductPrice` FLOAT NULL,
  `Material` INT NULL,
  PRIMARY KEY (`ProductID`),
  INDEX `Material_idx` (`Material` ASC),
  CONSTRAINT `Material`
    FOREIGN KEY (`Material`)
    REFERENCES `mydb`.`Materials` (`MaterialID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TransactionInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TransactionInfo` (
  `TransactionID` INT NOT NULL,
  `Product` INT NULL,
  `ProductQuantity` INT NULL,
  PRIMARY KEY (`TransactionID`),
  INDEX `ProductID_idx` (`Product` ASC),
  CONSTRAINT `TransactionID`
    FOREIGN KEY (`TransactionID`)
    REFERENCES `mydb`.`Transactions` (`TransactionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ProductID`
    FOREIGN KEY (`Product`)
    REFERENCES `mydb`.`Products` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Inventory` (
  `InventoryDataTime` DATETIME(6) NOT NULL,
  `InventoryEmployee` INT NULL,
  PRIMARY KEY (`InventoryDataTime`),
  INDEX `InventoryEmployee_idx` (`InventoryEmployee` ASC),
  CONSTRAINT `InventoryEmployee`
    FOREIGN KEY (`InventoryEmployee`)
    REFERENCES `mydb`.`Employees` (`EmployeeID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`InventoryInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`InventoryInfo` (
  `InventoryDateTime` DATETIME(6) NULL,
  `Material` INT NOT NULL,
  `MaterialQuantity` INT NULL,
  `MaterialQuantitySold` INT NULL,
  INDEX `InventoryDateTime_idx` (`InventoryDateTime` ASC),
  INDEX `Material_idx` (`Material` ASC),
  PRIMARY KEY (`Material`),
  CONSTRAINT `InventoryDateTime`
    FOREIGN KEY (`InventoryDateTime`)
    REFERENCES `mydb`.`Inventory` (`InventoryDataTime`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Material`
    FOREIGN KEY (`Material`)
    REFERENCES `mydb`.`Materials` (`MaterialID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
